---
title: while-loop
---
flowchart TD
	null$28("__tmp$12 = v$3<br>__tmp$13 = 0<br>__tmp$14 = (__tmp$12 > 0)<br>ploop1-1$4 = 0<br>ploop1-2$4 = (__tmp$12 > 0)"):::defstyle
	cond$26{"ploop1-2$1"}:::defstyle
	entry$24("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (35 + 1)<br>v$0 = (35 + 1)<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > 0)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > 0)"):::defstyle
	while_body$27("__tmp$7 = 1<br>v$3 = (v$1 - 1)<br>__tmp$6 = v$1<br>__tmp$8 = v$3<br>__tmp$9 = print$0<br>__tmp$10 = print$0(v$3)"):::defstyle
	while_start$25("v$1 = φ(v$3, v$0)<br>ploop1-1$1 = φ(ploop1-1$4, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$4, ploop1-2$0)"):::defstyle
	while_exit$29("exit"):::defstyle
	while_start$25 -->  cond$26
	cond$26 --> |"true"| while_body$27
	cond$26 --> |"false"| while_exit$29
	entry$24 -->  while_start$25
	null$28 -->  while_start$25
	while_body$27 -->  null$28
classDef defstyle text-align: left;
