---
title: while-break-loop
---
flowchart TD
	while_start$41("v$1 = φ(v$3, v$0)<br>ploop1-1$1 = φ(ploop1-1$7, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$7, ploop1-2$0)"):::defstyle
	if_merged$48("__tmp$14 = v$3<br>__tmp$15 = print$0<br>__tmp$16 = print$0(v$3)"):::defstyle
	entry$40("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (35 + 1)<br>v$0 = (35 + 1)<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > 0)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > 0)"):::defstyle
	while_body$43("__tmp$7 = 1<br>v$3 = (v$1 - 1)<br>__tmp$6 = v$1"):::defstyle
	cond$45{"(v$3 == 16)"}:::defstyle
	while_exit$47("exit"):::defstyle
	cond$42{"ploop1-2$1"}:::defstyle
	null$49("__tmp$18 = v$3<br>__tmp$19 = 0<br>__tmp$20 = (__tmp$18 > 0)<br>ploop1-1$7 = 0<br>ploop1-2$7 = (__tmp$18 > 0)"):::defstyle
	if_true$46("_"):::defstyle
	if_cond$44("__tmp$11 = v$3<br>__tmp$12 = 16<br>__tmp$13 = (v$3 == 16)"):::defstyle
	if_merged$48 -->  null$49
	while_start$41 -->  cond$42
	if_true$46 -->  while_exit$47
	null$49 -->  while_start$41
	if_cond$44 -->  cond$45
	entry$40 -->  while_start$41
	cond$45 --> |"true"| if_true$46
	while_body$43 -->  if_cond$44
	cond$42 --> |"false"| while_exit$47
	cond$42 --> |"true"| while_body$43
	cond$45 --> |"false"| if_merged$48
classDef defstyle text-align: left;
