---
title: while-break-loop
---
flowchart TD
	while_start$21("v$1 = φ(v$3, v$0)<br>ploop1-1$1 = φ(ploop1-1$7, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$7, ploop1-2$0)"):::defstyle
	while_body$23("__tmp$7 = 1<br>v$3 = (v$1 - __tmp$7)<br>__tmp$6 = v$1"):::defstyle
	entry$20("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (__tmp$0 + __tmp$1)<br>v$0 = __tmp$2<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > __tmp$4)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > __tmp$4)"):::defstyle
	null$29("__tmp$18 = v$3<br>__tmp$19 = 0<br>__tmp$20 = (__tmp$18 > __tmp$19)<br>ploop1-1$7 = 0<br>ploop1-2$7 = (__tmp$18 > __tmp$19)"):::defstyle
	cond$22{"ploop1-2$1"}:::defstyle
	cond$25{"__tmp$13"}:::defstyle
	if_cond$24("__tmp$11 = v$3<br>__tmp$12 = 16<br>__tmp$13 = (__tmp$11 == __tmp$12)"):::defstyle
	while_exit$27("exit"):::defstyle
	if_merged$28("__tmp$14 = v$3<br>__tmp$15 = print$0<br>__tmp$16 = __tmp$15(__tmp$14)"):::defstyle
	if_true$26("_"):::defstyle
	cond$25 --> |"true"| if_true$26
	if_true$26 -->  while_exit$27
	while_body$23 -->  if_cond$24
	entry$20 -->  while_start$21
	cond$25 --> |"false"| if_merged$28
	if_merged$28 -->  null$29
	while_start$21 -->  cond$22
	cond$22 --> |"false"| while_exit$27
	if_cond$24 -->  cond$25
	null$29 -->  while_start$21
	cond$22 --> |"true"| while_body$23
classDef defstyle text-align: left;
