---
title: while-break-loop
---
flowchart TD
	if_true$16("_"):::defstyle
	if_merged$18("__tmp$14 = v$3<br>__tmp$15 = print$0<br>__tmp$16 = print$0(v$3)"):::defstyle
	while_start$11("v$1 = φ(v$3, v$0)<br>ploop1-1$1 = φ(ploop1-1$7, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$7, ploop1-2$0)"):::defstyle
	entry$10("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (35 + 1)<br>v$0 = (35 + 1)<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > 0)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > 0)"):::defstyle
	cond$12{"ploop1-2$1"}:::defstyle
	null$19("__tmp$18 = v$3<br>__tmp$19 = 0<br>__tmp$20 = (__tmp$18 > 0)<br>ploop1-1$7 = 0<br>ploop1-2$7 = (__tmp$18 > 0)"):::defstyle
	cond$15{"(v$3 == 16)"}:::defstyle
	if_cond$14("__tmp$11 = v$3<br>__tmp$12 = 16<br>__tmp$13 = (v$3 == 16)"):::defstyle
	while_body$13("__tmp$7 = 1<br>v$3 = (v$1 - 1)<br>__tmp$6 = v$1"):::defstyle
	while_exit$17("exit"):::defstyle
	cond$12 --> |"true"| while_body$13
	if_true$16 -->  while_exit$17
	null$19 -->  while_start$11
	entry$10 -->  while_start$11
	if_merged$18 -->  null$19
	while_body$13 -->  if_cond$14
	cond$15 --> |"false"| if_merged$18
	if_cond$14 -->  cond$15
	cond$15 --> |"true"| if_true$16
	while_start$11 -->  cond$12
	cond$12 --> |"false"| while_exit$17
classDef defstyle text-align: left;
