---
title: while-continue-loop
---
flowchart TD
	if_merged$8("ploop1-2$5 = φ(ploop1-2$3)<br>ploop1-1$5 = φ(ploop1-1$3)<br>v$6 = φ(v$4)<br>__tmp$14 = v$6<br>__tmp$15 = print$0<br>__tmp$16 = __tmp$15(__tmp$14)"):::defstyle
	while_start$1("v$1 = φ(v$4, v$0, v$7)<br>ploop1-1$1 = φ(ploop1-1$3, ploop1-1$7, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$3, ploop1-2$7, ploop1-2$0)"):::defstyle
	entry$0("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (__tmp$0 + __tmp$1)<br>v$0 = __tmp$2<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > __tmp$4)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > __tmp$4)"):::defstyle
	while_body$3("ploop1-2$2 = φ(ploop1-2$1)<br>ploop1-1$2 = φ(ploop1-1$1)<br>v$2 = φ(v$1)<br>__tmp$7 = 1<br>v$3 = (v$2 - __tmp$7)<br>__tmp$6 = v$2"):::defstyle
	if_cond$4("__tmp$10 = φ(__tmp$6)<br>v$5 = φ(v$3)<br>ploop1-1$4 = φ(ploop1-1$2)<br>ploop1-2$4 = φ(ploop1-2$2)<br>__tmp$11 = v$5<br>__tmp$12 = 16<br>__tmp$13 = (__tmp$11 == __tmp$12)"):::defstyle
	cond$5{"__tmp$13"}:::defstyle
	while_exit$9("v$8 = φ(v$1)<br>ploop1-1$8 = φ(ploop1-1$1)<br>ploop1-2$8 = φ(ploop1-2$1)"):::defstyle
	cond$2{"ploop1-2$1"}:::defstyle
	if_true$6("__tmp$8 = φ(__tmp$6)<br>v$4 = φ(v$3)<br>ploop1-1$3 = φ(ploop1-1$2)<br>ploop1-2$3 = φ(ploop1-2$2)"):::defstyle
	null$7("__tmp$17 = φ(__tmp$16)<br>v$7 = φ(v$6)<br>ploop1-1$6 = φ(ploop1-1$5)<br>ploop1-2$6 = φ(ploop1-2$5)<br>__tmp$18 = v$7<br>__tmp$19 = 0<br>__tmp$20 = (__tmp$18 > __tmp$19)<br>ploop1-1$7 = 0<br>ploop1-2$7 = (__tmp$18 > __tmp$19)"):::defstyle
	if_merged$8 -->  null$7
	cond$5 --> |"false"| if_merged$8
	if_cond$4 -->  cond$5
	cond$5 --> |"true"| if_true$6
	while_start$1 -->  cond$2
	cond$2 --> |"true"| while_body$3
	null$7 -->  while_start$1
	entry$0 -->  while_start$1
	while_body$3 -->  if_cond$4
	cond$2 --> |"false"| while_exit$9
	if_true$6 -->  null$7
classDef defstyle text-align: left;
