flowchart TD
	while_start$10("v$1 = φ(v$3, v$0)<br>ploop0-1$1 = φ(ploop0-1$0)<br>ploop0-2$1 = φ(ploop0-2$0)")
	while_body$12("v$3 = (v$1 - 1)<br>__tmp$6 = v$1")
	if_true$15("__tmp$9 = ContinueExpr(label=null)")
	cond$14{"(v$3 == 16)"}
	entry$9("v$0 = (35 + 1)<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > 0)<br>ploop0-1$0 = 0<br>ploop0-2$0 = (__tmp$3 > 0)")
	if_merged$16("__tmp$16 = print$0(v$3)")
	cond$11{"ploop0-2$1"}
	if_cond$13(" ")
	while_exit$17("exit")
	if_merged$16 -->  while_start$10
	if_cond$13 -->  cond$14
	while_start$10 -->  cond$11
	if_true$15 -->  while_start$10
	cond$14 --> |"true"| if_true$15
	cond$14 --> |"false"| if_merged$16
	cond$11 --> |"false"| while_exit$17
	while_body$12 -->  if_cond$13
	cond$11 --> |"true"| while_body$12
	entry$9 -->  while_start$10
