---
title: while-continue-loop
---
flowchart TD
	while_start$31("v$1 = φ(v$3, v$0)<br>ploop1-1$1 = φ(ploop1-1$7, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$7, ploop1-2$0)"):::defstyle
	if_merged$38("__tmp$14 = v$3<br>__tmp$15 = print$0<br>__tmp$16 = print$0(v$3)"):::defstyle
	entry$30("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (35 + 1)<br>v$0 = (35 + 1)<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > 0)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > 0)"):::defstyle
	cond$32{"ploop1-2$1"}:::defstyle
	while_body$33("__tmp$7 = 1<br>v$3 = (v$1 - 1)<br>__tmp$6 = v$1"):::defstyle
	cond$35{"(v$3 == 16)"}:::defstyle
	null$37("__tmp$18 = v$3<br>__tmp$19 = 0<br>__tmp$20 = (__tmp$18 > 0)<br>ploop1-1$7 = 0<br>ploop1-2$7 = (__tmp$18 > 0)"):::defstyle
	if_true$36("_"):::defstyle
	if_cond$34("__tmp$11 = v$3<br>__tmp$12 = 16<br>__tmp$13 = (v$3 == 16)"):::defstyle
	while_exit$39("exit"):::defstyle
	entry$30 -->  while_start$31
	while_start$31 -->  cond$32
	if_merged$38 -->  null$37
	cond$32 --> |"true"| while_body$33
	null$37 -->  while_start$31
	cond$35 --> |"true"| if_true$36
	while_body$33 -->  if_cond$34
	cond$32 --> |"false"| while_exit$39
	if_cond$34 -->  cond$35
	if_true$36 -->  null$37
	cond$35 --> |"false"| if_merged$38
classDef defstyle text-align: left;
