---
title: while-complex-loop
---
flowchart TD
	if_cond$118("__tmp$37 = x$0<br>__tmp$38 = 2<br>__tmp$39 = (x$0 % 2)<br>__tmp$40 = 0<br>__tmp$41 = ((x$0 % 2) == 0)"):::defstyle
	entry$96("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (35 + 1)<br>v$0 = (35 + 1)<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > 0)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > 0)"):::defstyle
	if_cond$100("__tmp$11 = v$3<br>__tmp$12 = 16<br>__tmp$13 = (v$3 == 16)"):::defstyle
	cond$119{"((x$0 % 2) == 0)"}:::defstyle
	null$103("__tmp$54 = v$10<br>__tmp$55 = 0<br>__tmp$56 = (__tmp$54 > 0)<br>ploop1-1$9 = 0<br>ploop1-2$9 = (__tmp$54 > 0)"):::defstyle
	if_merged$125("_"):::defstyle
	if_true$120("__tmp$32 = 1<br>v$16 = (v$10 + 1)<br>__tmp$31 = v$10"):::defstyle
	cond$114{"(v$10 == 1)"}:::defstyle
	cond$101{"(v$3 == 16)"}:::defstyle
	while_start$110("xx$1 = φ(xx$0, xx$6)<br>v$10 = φ(v$20, v$3)<br>ploop2-2$1 = φ(ploop2-2$14, ploop2-2$0)"):::defstyle
	cond$98{"ploop1-2$1"}:::defstyle
	if_true$115("_"):::defstyle
	cond$111{"ploop2-2$1"}:::defstyle
	if_true$107("_"):::defstyle
	cond$123{"(xx$6 == 55)"}:::defstyle
	if_cond$122("__tmp$44 = xx$6<br>__tmp$45 = 55<br>__tmp$46 = (xx$6 == 55)"):::defstyle
	if_merged$117("__tmp$29 = 1<br>xx$6 = (xx$1 - 1)<br>__tmp$28 = xx$1"):::defstyle
	if_merged$109("__tmp$18 = v$3<br>__tmp$19 = 2<br>__tmp$20 = (v$3 * 2)<br>xx$0 = (v$3 * 2)<br>__tmp$21 = xx$0<br>__tmp$22 = v$3<br>__tmp$23 = (__tmp$21 > __tmp$22)<br>ploop2-2$0 = (__tmp$21 > __tmp$22)"):::defstyle
	if_cond$105("__tmp$15 = v$3<br>__tmp$16 = 44<br>__tmp$17 = (v$3 == 44)"):::defstyle
	if_false$127("__tmp$35 = 1<br>v$18 = (v$10 - 1)<br>__tmp$34 = v$10"):::defstyle
	if_merged$121("__tmp$42 = φ(__tmp$34, __tmp$31)<br>v$20 = φ(v$18, v$16)"):::defstyle
	if_true$102("_"):::defstyle
	if_true$124("_"):::defstyle
	if_merged$104("_"):::defstyle
	if_cond$113("__tmp$25 = v$10<br>__tmp$26 = 1<br>__tmp$27 = (v$10 == 1)"):::defstyle
	cond$106{"(v$3 == 44)"}:::defstyle
	while_body$112("_"):::defstyle
	while_start$97("v$1 = φ(v$3, v$0, v$10)<br>ploop1-1$1 = φ(ploop1-1$9, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$9, ploop1-2$0)"):::defstyle
	while_exit$116("__tmp$50 = v$10<br>__tmp$51 = print$0<br>__tmp$52 = print$0(v$10)"):::defstyle
	null$126("__tmp$47 = xx$6<br>__tmp$48 = v$20<br>__tmp$49 = (__tmp$47 > __tmp$48)<br>ploop2-2$14 = (__tmp$47 > __tmp$48)"):::defstyle
	while_body$99("__tmp$7 = 1<br>v$3 = (v$1 - 1)<br>__tmp$6 = v$1"):::defstyle
	while_exit$108("exit"):::defstyle
	if_false$127 -->  if_merged$121
	null$103 -->  while_start$97
	if_merged$117 -->  if_cond$118
	entry$96 -->  while_start$97
	cond$123 --> |"true"| if_true$124
	cond$106 --> |"false"| if_merged$109
	if_true$107 -->  while_exit$108
	cond$119 --> |"true"| if_true$120
	while_exit$116 -->  null$103
	if_true$124 -->  while_exit$116
	if_merged$125 -->  null$126
	if_true$120 -->  if_merged$121
	if_cond$100 -->  cond$101
	if_merged$109 -->  while_start$110
	if_merged$121 -->  if_cond$122
	if_merged$104 -->  if_cond$105
	if_cond$105 -->  cond$106
	if_cond$118 -->  cond$119
	cond$123 --> |"false"| if_merged$125
	cond$111 --> |"false"| while_exit$116
	while_body$112 -->  if_cond$113
	if_cond$113 -->  cond$114
	null$126 -->  while_start$110
	cond$111 --> |"true"| while_body$112
	while_body$99 -->  if_cond$100
	cond$98 --> |"false"| while_exit$108
	cond$114 --> |"true"| if_true$115
	cond$114 --> |"false"| if_merged$117
	while_start$110 -->  cond$111
	cond$106 --> |"true"| if_true$107
	cond$98 --> |"true"| while_body$99
	cond$119 --> |"false"| if_false$127
	if_cond$122 -->  cond$123
	cond$101 --> |"false"| if_merged$104
	while_start$97 -->  cond$98
	if_true$115 -->  while_exit$116
	if_true$102 -->  null$103
	cond$101 --> |"true"| if_true$102
classDef defstyle text-align: left;
