---
title: while-complex-loop
---
flowchart TD
	cond$87{"__tmp$41"}:::defstyle
	if_merged$93("_"):::defstyle
	if_true$75("_"):::defstyle
	if_cond$90("__tmp$44 = xx$6<br>__tmp$45 = 55<br>__tmp$46 = (__tmp$44 == __tmp$45)"):::defstyle
	cond$82{"__tmp$27"}:::defstyle
	if_true$70("_"):::defstyle
	null$71("__tmp$54 = v$10<br>__tmp$55 = 0<br>__tmp$56 = (__tmp$54 > __tmp$55)<br>ploop1-1$9 = 0<br>ploop1-2$9 = (__tmp$54 > __tmp$55)"):::defstyle
	if_true$92("_"):::defstyle
	if_merged$72("_"):::defstyle
	cond$66{"ploop1-2$1"}:::defstyle
	if_cond$86("__tmp$37 = x$0<br>__tmp$38 = 2<br>__tmp$39 = (__tmp$37 % __tmp$38)<br>__tmp$40 = 0<br>__tmp$41 = (__tmp$39 == __tmp$40)"):::defstyle
	if_cond$73("__tmp$15 = v$3<br>__tmp$16 = 44<br>__tmp$17 = (__tmp$15 == __tmp$16)"):::defstyle
	if_merged$77("__tmp$18 = v$3<br>__tmp$19 = 2<br>__tmp$20 = (__tmp$18 * __tmp$19)<br>xx$0 = __tmp$20<br>__tmp$21 = xx$0<br>__tmp$22 = v$3<br>__tmp$23 = (__tmp$21 > __tmp$22)<br>ploop2-2$0 = (__tmp$21 > __tmp$22)"):::defstyle
	if_true$88("__tmp$32 = 1<br>v$16 = (v$10 + __tmp$32)<br>__tmp$31 = v$10"):::defstyle
	cond$79{"ploop2-2$1"}:::defstyle
	if_merged$85("__tmp$29 = 1<br>xx$6 = (xx$1 - __tmp$29)<br>__tmp$28 = xx$1"):::defstyle
	while_body$67("__tmp$7 = 1<br>v$3 = (v$1 - __tmp$7)<br>__tmp$6 = v$1"):::defstyle
	entry$64("__tmp$0 = 35<br>__tmp$1 = 1<br>__tmp$2 = (__tmp$0 + __tmp$1)<br>v$0 = __tmp$2<br>__tmp$3 = v$0<br>__tmp$4 = 0<br>__tmp$5 = (__tmp$3 > __tmp$4)<br>ploop1-1$0 = 0<br>ploop1-2$0 = (__tmp$3 > __tmp$4)"):::defstyle
	while_exit$76("exit"):::defstyle
	if_merged$89("__tmp$42 = φ(__tmp$34, __tmp$31)<br>v$20 = φ(v$18, v$16)"):::defstyle
	cond$69{"__tmp$13"}:::defstyle
	while_start$78("xx$1 = φ(xx$0, xx$6)<br>v$10 = φ(v$20, v$3)<br>ploop2-2$1 = φ(ploop2-2$14, ploop2-2$0)"):::defstyle
	while_exit$84("__tmp$50 = v$10<br>__tmp$51 = print$0<br>__tmp$52 = __tmp$51(__tmp$50)"):::defstyle
	null$94("__tmp$47 = xx$6<br>__tmp$48 = v$20<br>__tmp$49 = (__tmp$47 > __tmp$48)<br>ploop2-2$14 = (__tmp$47 > __tmp$48)"):::defstyle
	cond$74{"__tmp$17"}:::defstyle
	cond$91{"__tmp$46"}:::defstyle
	while_start$65("v$1 = φ(v$3, v$0, v$10)<br>ploop1-1$1 = φ(ploop1-1$9, ploop1-1$0)<br>ploop1-2$1 = φ(ploop1-2$9, ploop1-2$0)"):::defstyle
	if_true$83("_"):::defstyle
	while_body$80("_"):::defstyle
	if_false$95("__tmp$35 = 1<br>v$18 = (v$10 - __tmp$35)<br>__tmp$34 = v$10"):::defstyle
	if_cond$68("__tmp$11 = v$3<br>__tmp$12 = 16<br>__tmp$13 = (__tmp$11 == __tmp$12)"):::defstyle
	if_cond$81("__tmp$25 = v$10<br>__tmp$26 = 1<br>__tmp$27 = (__tmp$25 == __tmp$26)"):::defstyle
	entry$64 -->  while_start$65
	if_cond$90 -->  cond$91
	cond$87 --> |"true"| if_true$88
	cond$79 --> |"false"| while_exit$84
	cond$82 --> |"false"| if_merged$85
	if_true$75 -->  while_exit$76
	null$71 -->  while_start$65
	if_true$83 -->  while_exit$84
	if_true$88 -->  if_merged$89
	cond$82 --> |"true"| if_true$83
	cond$66 --> |"false"| while_exit$76
	cond$74 --> |"true"| if_true$75
	if_cond$81 -->  cond$82
	if_merged$72 -->  if_cond$73
	cond$69 --> |"true"| if_true$70
	if_merged$77 -->  while_start$78
	cond$69 --> |"false"| if_merged$72
	if_true$92 -->  while_exit$84
	if_cond$68 -->  cond$69
	cond$91 --> |"false"| if_merged$93
	if_true$70 -->  null$71
	if_cond$73 -->  cond$74
	if_merged$93 -->  null$94
	if_merged$85 -->  if_cond$86
	cond$74 --> |"false"| if_merged$77
	while_exit$84 -->  null$71
	cond$87 --> |"false"| if_false$95
	if_false$95 -->  if_merged$89
	cond$79 --> |"true"| while_body$80
	if_merged$89 -->  if_cond$90
	if_cond$86 -->  cond$87
	while_body$80 -->  if_cond$81
	while_start$78 -->  cond$79
	while_start$65 -->  cond$66
	cond$66 --> |"true"| while_body$67
	cond$91 --> |"true"| if_true$92
	while_body$67 -->  if_cond$68
	null$94 -->  while_start$78
classDef defstyle text-align: left;
